project:
  type: book
  output-dir: docs

book:
  title: "weekly diary"
  author: "Norah Jones"
  date: "2025/2/4"
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

